// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJf0VGeTQXeW5lEECp2pJDZge2CHTMOeA',
    appId: '1:837771691150:web:d336f154e160d95368f5df',
    messagingSenderId: '837771691150',
    projectId: 'fitlab-435d6',
    authDomain: 'fitlab-435d6.firebaseapp.com',
    storageBucket: 'fitlab-435d6.appspot.com',
    measurementId: 'G-0MJQ9DZ1VE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOfY_ATznXUiUMcg_kl_nXNA5DaT3Ntoo',
    appId: '1:837771691150:android:8a89ef5055aa41ff68f5df',
    messagingSenderId: '837771691150',
    projectId: 'fitlab-435d6',
    storageBucket: 'fitlab-435d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlPzk38NJbo6CSOSNb0AeffY4rfTjo8vc',
    appId: '1:837771691150:ios:6ca3c319b10c9bca68f5df',
    messagingSenderId: '837771691150',
    projectId: 'fitlab-435d6',
    storageBucket: 'fitlab-435d6.appspot.com',
    iosClientId: '837771691150-3ajnbgtqhbd6opvoroqj54pk550tug6i.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitLab1',
  );
}
